Add install instructions through cask
marcboquet/PlayNow pull request #4
Opened 2016-09-22 16:34 UTC by ronanrodrigo

I created a cask for the project :) https://github.com/caskroom/homebrew-cask/pull/24730

2016-09-25 17:45 UTC, marcboquet commented on README.md
> +3. Install OpenSim: `brew cask install playnow`
Should say "PlayNow" instead of "OpenSim"

2016-09-25 17:45 UTC, marcboquet requested changes
Thanks! Just a small change

2016-09-25 19:05 UTC, ronanrodrigo commented on README.md
> +3. Install OpenSim: `brew cask install playnow`
Ops. Done :)

2016-09-26 09:31 UTC, marcboquet approved these changes

2016-09-26 09:31 UTC, merged